# Netlify yapılandırma dosyası
[build]
  command = "CI=false npm run build"  # Build komutu - CI=false uyarıları hata olarak görmemesi için eklendi
  publish = "build"          # Yayınlanacak klasör
  functions = "netlify/functions"  # Netlify fonksiyonlarının bulunduğu klasör

# SPA yönlendirme kuralları - React Router için gerekli
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API endpoint'leri için yönlendirme
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Çevre değişkenleri (hassas değerler Netlify UI üzerinden ayarlanmalıdır)
[build.environment]
  NODE_VERSION = "18"  # Node.js sürümü

# Varsayılan HTTP başlıkları - Güvenlik için
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # Google Generative AI API'sı için gerekli bağlantılara izin ver
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.netlify.app *.netlify.com https://generativelanguage.googleapis.com; img-src 'self' data: blob:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';" 