[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

# Redirect and rewrite rules to handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirect for API endpoints
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Environment variables (sensitive values should be set in Netlify UI)
[build.environment]
  NODE_VERSION = "18"

# Set default headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.netlify.app *.netlify.com; img-src 'self' data: blob:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';" 